## mount plugin
[[manager.prepend_keymap]]
on   = "M"
run  = "plugin mount" #--args=/path/to/mmtui"
desc = "Mount manager"


## clipboard-plugin
# Copy yanked files to the system clipboard
[[mgr.prepend_keymap]]
on  = "y"
run = [ "yank", 'plugin clipboard -- --action=copy' ]

# Paste files from the system clipboard into the current directory
[[mgr.prepend_keymap]]
on  = "<C-p>"
run = [ 'plugin clipboard -- --action=paste' ]
